server:
  # 服务器接受连接的端口
  port: 9002
  # 启用优雅关机
  shutdown: graceful
  netty:
    # 与服务器建立 TCP 连接的等待时间
    connection-timeout: 2s
    # 如果没有数据传输，关闭 TCP 连接前的等待时间
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
    # 定义 15 秒的宽限期
    timeout-per-shutdown-phase: 15s
  r2dbc:
    # 具有访问给定数据库权限的用户
    username: user
    # 给定用户的密码
    password: password
    # 表示要于哪个数据库建立连接的 R2DBC URL
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      # 从池中获取连接的最大等待时间
      max-create-connection-time: 2s
      # 连接池的初始大小
      initial-size: 5
      # 池中所持有的最大连接数
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order

# 为 Catalog Service 配置 URI
polar:
  catalog-service-uri: "http://localhost:9001"
