server:
  # 服务器接受连接的端口
  port: 9002
  # 启用优雅关机
  shutdown: graceful
  netty:
    # 与服务器建立 TCP 连接的等待时间
    connection-timeout: 2s
    # 如果没有数据传输，关闭 TCP 连接前的等待时间
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
    # 定义 15 秒的宽限期
    timeout-per-shutdown-phase: 15s
  r2dbc:
    # 具有访问给定数据库权限的用户
    username: user
    # 给定用户的密码
    password: password
    # 表示要于哪个数据库建立连接的 R2DBC URL
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      # 从池中获取连接的最大等待时间
      max-create-connection-time: 2s
      # 连接池的初始大小
      initial-size: 5
      # 池中所持有的最大连接数
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order
  config:
    # 如果配置服务器可用的话，会在这里导入配置数据
    import: "optional:configserver:"
  cloud:
    config:
      # 配置服务器的 URL
      uri: http://localhost:8888
      # 等待连接配置服务器的超时时间 (毫秒)
      request-connect-timeout: 5000
      # 等待从配置服务器读取配置数据的超时时间 (毫秒)
      request-read-timeout: 5000
      # 将连接至配置服务器的失败设置为致命错误
      fail-fast: true
      retry:
        # 最大的尝试次数
        max-attempts: 6
        # Backoff 的初始重试间隔 (毫秒)
        initial-interval: 1000
        # Backoff 的最大重试间隔 (毫秒)
        max-interval: 2000
        # 计算下一次间隔的乘数
        multiplier: 1.1
    function:
      # 定义由 Spring Cloud Function 管理的函数
      definition: dispatchOrder
    stream:
      bindings:
        # 输入绑定
        dispatchOrder-in-0:
          # 在代理中，绑定器绑定的实际名称 (RabbitMQ 中的交换机)
          destination: order-dispatched
          # 对目的地感兴趣的消费者组，与应用的名称相同
          group: ${spring.application.name}
        # StreamBridge 创建和管理的输出绑定
        acceptOrder-out-0:
          # 在代理中，绑定器绑定的实际名称 (RabbitMQ 中的交换机)
          destination: order-accepted
      # RabbitMQ 针对 Spring Cloud Stream 绑定所提供的配置
      rabbit:
        bindings:
          acceptOrder-out-0:
            producer:
              # 使 acceptOrder-out-0 绑定支持事务
              transacted: true
  # 配置与 RabbitMQ 的集成
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  security:
    oauth2:
      resourceserver:
        # OAuth2 并不强制要求访问令牌的格式，所以需要明确声明我们的选择。在本例中，我们想要使用 JWT
        jwt:
          # Keycloak URL 提供了特定 realm 的所有 OAuth2 相关端点的信息
          issuer-uri: http://localhost:8080/realms/PolarBookshop

# 为 Catalog Service 配置 URI
polar:
  catalog-service-uri: "http://localhost:9001"
